### ISSUE TITLE
Indent guide solid

### ISSUE THREAD

**Issue by jaredmoody** [jamiewilson/predawn-syntax#1]
The indent guide is a little intense. How about making it match the ST theme, being lighter and dotted?

Atom:
![albumexposure com 2014-09-25 16-11-18](https://cloud.githubusercontent.com/assets/27690/4413701/599caa4e-4509-11e4-8b31-8b7b5825424c.png)

ST:
![preferences sublime-settings albumexposure com 2014-09-25 16-12-32](https://cloud.githubusercontent.com/assets/27690/4413704/7161b8b8-4509-11e4-8cd9-916b76dd0b97.png)

**Comment by jaredmoody** [comment]
I played with it a bit and I like the same color but at 15% opacity:

```
.editor .indent-guide {
  color: rgba(241, 130, 96, 0.15);
}
```

![albumexposure com 2014-09-25 16-23-57](https://cloud.githubusercontent.com/assets/27690/4413798/09816bec-450b-11e4-9197-f878837f42d1.png)

```
```

**Comment by jamiewilson** [comment]
Thanks @jaredmoody, i just released a patch for this.
