### ISSUE TITLE
Deprecation warnings in Atom v1.13 and higher

### ISSUE THREAD

**Issue by MidnightLightning** [jamiewilson/predawn-syntax#12]
This extension now triggers a deprecation warning in current versions of Atom:

> Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

These should be updated in the source documents to prevent issues in future versions of Atom.

**Comment by p-chan** [comment]
Merged.
